### ISSUE TITLE
BadRequestHttpException

### ISSUE THREAD

**Issue by inzanty** [knojector/SteamAuthenticationBundle#4]
Symfony version: 5.3.3

Error calls when i enter on `steam/login_checks` route:
```
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_ns:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_mode:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_op_endpoint:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_claimed_id:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_identity:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_return_to:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_response_nonce:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_assoc_handle:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_signed:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_sig:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
```

security.yaml:
```yaml
security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        users:
            entity:
                class: 'App\Entity\Web\User'
                property: 'username'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        steam:
            pattern: ^/
            lazy: true
            provider: users

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
```

knojector_steam_authentication.yaml:
```yaml
# https://github.com/knojector/SteamAuthenticationBundle for configuration documentation
knojector_steam_authentication:
    login_success_redirect: 'app.protected_route'
    login_failure_redirect: 'app.error_route'
```
