### ISSUE TITLE
Error after click login on steam

### ISSUE THREAD

**Issue by MaxenceSAUNIER** [knojector/SteamAuthenticationBundle#6]
Hello,

I have add the button and if I click on it, I am redirect to steam. After i click on 'Login' on steam, I have this error. I'm in local.

`Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_op_endpoint:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_claimed_id:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_identity:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_return_to:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_response_nonce:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_assoc_handle:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_signed:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)
Object(Knojector\SteamAuthenticationBundle\DTO\SteamCallback).openid_sig:
This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)`

routes.yaml
```yaml
steam_authentication_callback:
  path: /steam/login_check
  controller: Knojector\SteamAuthenticationBundle\Controller\SteamController::callback
```

index.html.twig
```twig
{% extends 'base.html.twig' %}

{% block title %}Hello LoginPageController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {% include '@KnojectorSteamAuthentication/button.html.twig' %}
</div>
{% endblock %}

```

security.yaml
```yaml
security:
    # https://symfony.com/doc/current/security/authenticator_manager.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            #anonymous: true
            lazy: true
            provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        #- { path: ^/login, roles: PUBLIC_ACCESS }
        #- { path: ^/admin, roles: ROLE_ADMIN }

```

framework.yaml
```yaml
# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

```

```yaml
knojector_steam_authentication :
    login_success_redirect : ' app.protected_route '
    login_failure_redirect : ' app.error_route '
```

Thanks for your help.
Symfony 5.x
