### ISSUE TITLE
Zufällige Inkonsistenz beim Login

### ISSUE THREAD

**Issue by Thurston00** [knojector/SteamAuthenticationBundle#8]
Hey.

Ich benutze dieses Bundle mit Symfony 6.0.2 und habe festgestellt, dass ich zufällig folgende Fehlermeldung beim Versuch mich einzuloggen bekomme:

`https://localhost:8000/steam/login_check?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=error&openid.error=realm+and+return_to+do+not+match`

Screenshot von der Fehlermeldung:

![image](https://user-images.githubusercontent.com/39656403/150642656-c0476f41-0a40-481f-943a-f1d10d8dd249.png)

Das Wechseln von `127.0.0.1:8000´ zu ´localhost:8000´ löste vorerst das Problem. Jedoch habe ich dieses Problem nun sehr oft/jedes Mal. Ich habe keine Änderungen an der Domain und nur kleinere Änderungen an der Bundle config vorgenommen.

`knojector_steam_authentication.yaml`
```yaml
knojector_steam_authentication:
    login_success_redirect: 'dashboard'
    login_failure_redirect: 'login'
```

`routes.yaml`
```yaml
steam_authentication_callback:
  path: /steam/login_check
  controller: Knojector\SteamAuthenticationBundle\Controller\SteamController::callback
```

`FirstLoginSubscriber.php`
```php
class FirstLoginSubscriber implements EventSubscriberInterface
{
    public function __construct(private EventDispatcherInterface $eventDispatcher, private ManagerRegistry $managerRegistry, private UserService $userService) {}

    /**
     * @inheritDoc
     */
    public static function getSubscribedEvents()
    {
        return [
            FirstLoginEvent::NAME => 'onFirstLogin'
        ];
    }

    public function onFirstLogin(FirstLoginEvent $event)
    {
        $communityId = $event->getCommunityId();

        $details = $this->userService->getProfileDetailsFromSteam($communityId)->response->players[0];

        $user = (new User())
            ->setUsername($details->personaname)
            ->setSteamId($details->steamid)
            ->setAvatar($details->avatar)
            ->setAvatarMedium($details->avatarmedium)
            ->setAvatarFull($details->avatarfull)
            ->setProfileUrl($details->profileurl ?? null);

        $manager = $this->managerRegistry->getManager();

        $manager->persist($user);
        $manager->flush();

        $this->eventDispatcher->dispatch(new AuthenticateUserEvent($user), AuthenticateUserEvent::NAME);
    }
}
```

`security.yaml`
```yaml
    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'username'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        steam:
            pattern: ^/
            lazy: true
            provider: users
```

Ich habe in Tickets gesehen, dass auch andere Personen dieses Problem haben. Jedoch konnte ich dazu keine konkrete Lösung finden.
